cybervidyapeeth/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from cybervidyapeeth.production_setup import IS_PRODUCTION_SERVER
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if not IS_PRODUCTION_SERVER:
    if hasattr(settings, 'DEBUG') and settings.DEBUG:
        import debug_toolbar

        if hasattr(settings, 'DJANGO_DEBUG_TOOLBAR') and settings.DJANGO_DEBUG_TOOLBAR:
            urlpatterns += [
                re_path(r'^__debug__/', include(debug_toolbar.urls)),
            ]

website/urls.py
from django.urls import path,re_path
from . import views
from django.views.generic import TemplateView
#####  import statements above

app_name = 'website'

urlpatterns=[
	path(r'', views.HomeView.as_view(), name='home'),
	path(r'about-cyberversity/', \
		TemplateView.as_view(template_name='website/about_cyberversity.html'), name='about_cyberversity'),
	path(r'advisory-board/', \
		TemplateView.as_view(template_name='website/advisory_board.html'), name='advisory_board'),

	path(r'leadership/', \
		TemplateView.as_view(template_name='website/leadership.html'), name='leadership'),

	path(r'contactus/', \
		TemplateView.as_view(template_name='website/contactus.html'), name='contactus'),
 
	path(r'courses/', \
		TemplateView.as_view(template_name='website/courses.html'), name='courses'),
  
	path(r'corporate-trainings/', \
		TemplateView.as_view(template_name='website/corporate_trainings.html'), name='corporate_trainings'),
 
	path(r'internships/', \
		TemplateView.as_view(template_name='website/internships.html'), name='internships'),
 
	path(r'research/', \
		TemplateView.as_view(template_name='website/inner_page_template.html'), name='research'),
 
	path(r'education/', \
		TemplateView.as_view(template_name='website/inner_page_template.html'), name='education'),
 
	path(r'event/', \
		TemplateView.as_view(template_name='website/inner_page_template.html'), name='event'),
 
	path(r'courses/course-name/', \
		TemplateView.as_view(template_name='website/course_detail.html'), name='course_detail'),



	path(r'courses/advance-diploma-in-cyber-defense/', \
		TemplateView.as_view(template_name='website/advance_diploma_in_cyber_defense.html'), name='advance_diploma_in_cyber_defense'),


	path(r'courses/pg-diploma-in-cyber-defense/', \
		TemplateView.as_view(template_name='website/pg_diploma_in_cyber_defense.html'), name='pg_diploma_in_cyber_defense'),




	path(r'training/cyber-rakshak-beginner/', \
		TemplateView.as_view(template_name='website/cyber_rakshak_beginner.html'), name='cyber_rakshak_beginner'),



	path(r'partners/', \
		TemplateView.as_view(template_name='website/inner_page_template.html'), name='partners'),

    
	path(r'placements/', \
		TemplateView.as_view(template_name='website/inner_page_template.html'), name='placements'),

    
 
    

]

website/models.py
from django.db import models
from django.utils import timezone
from cybervidyapeeth import core_lib
from PIL import Image
from django.core.files import File
import os



class ActiveScriptStyleVersion(models.Model):
	id = models.CharField(max_length=24, primary_key=True, default=core_lib.generate_unique_object_id)
	version_no = models.CharField(max_length=100)

	def __str__(self):
			return self.version_no

website/views.py
from django.shortcuts import render
import website.handlers as website_handlers
from django.views.generic import View
from website.redirection_dict import redirection_dict, new_dict
from django.shortcuts import redirect
from django.urls import reverse
# Create your views here.
import os
from django.conf import settings
from django.http import HttpResponse

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return website_handlers.home_renderer(request)

website/templates/website/about_cyberversity.html
{% extends 'website/base.html' %}

{% block base_meta_block %}
	<!-- This Block Needs to be on every page of the Website -->
	<title> Cyber Vidyapeeth </title>
	<meta name="keywords" content="Cyber Vidyapeeth " />
	<meta name="description" content="Cyber Vidyapeeth " />
{% endblock%}

{% block base_head_block %}
{% endblock base_head_block %}
{% block base_block %}
<div class="inner_page_intro_header">
  <div class="shadeoverlay"></div>
  <div class="container">
    <div class="content">
      <h1 class=""> About Cybervidyapeeth  </h1>
      <!-- <h2 class=""> by Vajiram &amp; Ravi  </h2> -->
    </div>
  </div>
</div>

<div class="container py-5 page_content">
	<h3 class="text-warning">About Us</h3>
	<ul class=" ">
		<li class="">
			Cyber Vidyapeeth Foundation or CyberVersity has been up with focus on Education, Research and Training on Advanced Cyber Defense.
		</li>

		<li class="">
			CyberVersity is committed to creating a million Cyber Rakshak over next five years.
		</li>

		<li class="">
			CyberVersity team consist of  Cyber Engineering / Defense   Professionals from domains covering national defense, education, cyber defense &amp; Cyber Offense Capability.
		</li>

		<li class="">
			CyberVersity is all set to serve Bharat  and exhorts all Cyber Professionals, Academia and organizations to join its mission of Cyber Resilient Bharat.
		</li>

		<li class="">
			Do join us to see our common dream of “Cyber Resilient Bharat with Deep Cyber Offensive Capabilities.”
		</li>

	</ul>


	
				<h3 class="text-warning mt-4">Mission</h3>

				<p class="">
					The mission of the Cyber Vidyapeeth is to Provide Education, Training &amp; Research in the areas of Advance Cyber Defense. We shall create significantly large talent pool in Cyber Defense for Cyber Resilient Bharat.
				</p>

			

		
				<h2 class="text-warning mt-4">Vision</h2>

				<p class="">
					With the mission stated above, the Foundation has envisioned to
				</p>
				<ul>
					<li>Become the leading Education, Training and Research Organization in the areas of Cyber Defence & Related Technologies Including Data Science, Artificial Intelligence, Machine Learning, 5G, IoT, Block Chain, Quantum Computing</li>
					<li>Support universities, institutes, colleges, education boards and similar entities to architect, improve & enhance the Cyber Defense curricula and Train the trainer for easy adoption of new syllabus</li>
					<li>Promote discourse & discussion on Cyber Defense & Related Technologies to ignite idea creation among the academia, students and cyber professionals</li>
					<li>Mentor budding talent to infuse academic & technological excellence for creating next-generation Cyber Rakshak for Bharat</li>
				</ul>

			

</div>

{% endblock base_block %}

website/templates/website/contactus.html
{% extends 'website/base.html' %}
{% load static%}
{% block base_meta_block %}
	<!-- This Block Needs to be on every page of the Website -->
	<title> Cyber Vidyapeeth </title>
	<meta name="keywords" content="Cyber Vidyapeeth " />
	<meta name="description" content="Cyber Vidyapeeth " />
{% endblock%}

{% block base_head_block %}
{% endblock base_head_block %}
{% block base_block %}
<div class="inner_page_intro_header">
  <div class="shadeoverlay"></div>
  <div class="container">
    <div class="content">
      <h1 class=""> Contact Us </h1>
    </div>
  </div>
</div>

<div class="container py-5 page_content">
	<div class="mdp-map">
		<iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=28.432530,77.302659+(Cyber%20Vidyapeeth%E2%84%A2)&amp;t=&amp;z=16&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe>
		
	</div>

	<div class="mt-4">
		<div class=" ">
			<div class="row">
				<div class="col-md-12 bg-gray p-3">
					<form class="form flat_form ajax_form refresh_on_success" action="">
						{% csrf_token %}
						<div class="form-loader hidden ">
					      <p><i class="fa fa-pulse fa-spinner "></i><br/>
					      <span class="font-16">Please Wait ...</span></p>
					    </div>

						<div class="row">
							<div class="col-sm-6">
								<div class="form-group">
									<label> Name  <span class="text-danger">*</span></label>
									<input type="text" name="name" class="form-control" placeholder="Enter Your Name " value="{{cv.course_chapter.name}}" />
									<div class="help-text"></div>
								</div>
							</div>
							<div class="col-sm-6">
								<div class="form-group">
									<label> Email  <span class="text-danger">*</span></label>
									<input type="text" name="name" class="form-control" placeholder="Enter Your Email ID " value="{{cv.course_chapter.name}}" />
									<div class="help-text"></div>
								</div>
							</div>
						</div>

						

						
						<div class="form-group">
							<label> Mobile  <span class="text-danger">*</span></label>
							<input type="text" name="name" class="form-control" placeholder="Enter Your Email ID " value="{{cv.course_chapter.name}}" />
							<div class="help-text"></div>
						</div>

						<div class="form-group">
							<label> Subject  <span class="text-danger">*</span></label>
							<input type="text" name="name" class="form-control" placeholder="Enter Subject " value="{{cv.course_chapter.name}}" />
							<div class="help-text"></div>
						</div>
						
						<div class="form-group">
							<label> Message  <span class="text-danger">*</span></label>
							<textarea class="form-control" rows="3"></textarea>
							<div class="help-text"></div>
						</div>

							


							
						<div class="text-right">
							<button type="submit" class="btn submit_btn btn-primary d-block ">
						        <span  class="spinner-border spinner-border-md spinner-border-thin btn_loader mr-1 d-none"></span>
						        <span class="btn_text">Submit</span>
						    </button>
					  </div>
					</form>
				</div>

				
			</div>
	</div>

</div>

{% endblock base_block %}

website/templates/website/home.html
{% extends 'website/base.html' %}
{% load static %}
{% load custom_tags_filters %}

{% block base_meta_block %}
	<!-- This Block Needs to be on every page of the Website -->
	<title> Cyber Vidyapeeth </title>
	<meta name="keywords" content="Cyber Vidyapeeth " />
	<meta name="description" content="Cyber Vidyapeeth " />

	<!--  OG Tags  -->
	<meta property="og:type" content="website" />
	<meta property="og:title" content="Cyber Vidyapeeth&trade;" />
	<meta property="og:description" content="Cyber Vidyapeeth" />
	<meta property="og:image" content="https://cybervidyapeeth.com{% static 'cybervidyapeeth/images/og_image.png' %}" />
	<meta property="og:site_name" content="cybervidyapeeth.com" />
	<!--  OG Tags  -->

	<!--  Twitter Tags  -->
	<meta name="twitter:card" content="summary" />
	<meta name="twitter:title" content="Cyber Vidyapeeth&trade;" />
	<meta name="twitter:description" content="Cyber Vidyapeeth" />
	<meta name="twitter:image" content="https://cybervidyapeeth.in{% static 'cybervidyapeeth/images/og_image.png' %}" />
	<!--  Twitter Tags  -->
{% endblock base_meta_block %}

{% block base_head_block %}
<link rel="stylesheet" href="{% static 'cybervidyapeeth/libraries/OwlCarousel2-2.3.4/dist/assets/owl.carousel.min.css' %}" defer />
<link rel="stylesheet" href="{% static 'cybervidyapeeth/libraries/OwlCarousel2-2.3.4/dist/assets/owl.theme.default.min.css' %}" defer />
{% endblock base_head_block %}

{% block base_block %}
<!-- <header id="home" class="home_header " data-style="default" data-scroll-arrow="true">
  <div class="header-hero d-flex aligsn-items-center text-light">
		<div class="container  ">
			<div class="row">
				<div class="col-md-7">
					<h3>Welcome to</h3>
					
					<h1><div class="text-warning">Cybervidyapeeth <small class="text-white">TM </small></div></h1>
					<h4>World's First Dedicated online Cyber University</h4>
					<h5 class="mt-4">CyberVidyapeeth's <span class="font-weight-800 text-warning">CyberVersity</span> is on a mission to create 1 Million Cyber Rakshaks for India over the next 5 years. </h5>
					<h5 class="mt-4"> We have partnered with over 100 Corporations to place our trained CyberRakshaks </h5>
				</div>
				<div class="col-md-5 text-center">
						<div class="d-inline-block align-center position-relative">
							<div class="hero_img hero_img_1"><img src="{% static 'cybervidyapeeth/images/cybervidyapeeth-square.png' %}" /></div>
							<div class="hero_img hero_img_2"><img src="{% static 'cybervidyapeeth/images/cybervidyapeeth-square.png' %}" /></div>
							<div class="hero_img hero_img_3"><img src="{% static 'cybervidyapeeth/images/hacker.png' %}" /></div>
						</div>
				</div>
			</div>
	  </div>
	</div>

	<div class="overlay hero-shape fadeIn ad-100ms"></div>
	      
</header> -->
<div class="home_jumbo">
	<div class="container ">
			<div class="row">
				<div class="col-lg-7 left_col">
					<!-- <h3>Welcome to</h3> -->
					
					<h1><div class="text-warning">Cybervidyapeeth </div></h1>
					<h4>Education Entiity Dedicated to Cyber Defence</h4>
					<h5 class="mt-5">CyberVidyapeeth's <span class="font-weight-800 text-warning">CyberVersity</span> is on a mission to create 1 Million Cyber Rakshaks for India over the next 5 years. </h5>
					<!-- <h5 class="mt-4"> We have partnered with over 100 Corporations to place our trained CyberRakshaks </h5> -->
				</div>
				<div class="d-none d-sm-none d-md-block col-md-5 text-center ">
						<div class="h-100 align-items-center justify-content-center d-flex">
							<img src="{% static 'cybervidyapeeth/images/cybervidyapeeth-square.png' %}" class="hero_img "/>
						</div>
				</div>
			</div>
	  </div>
	  <div class="overlay hero-shape fadeIn ad-100ms"></div>
</div>



<section class="h-section">

	<div class="container features_shift_up mb-5" style="">
		<div class="row align-items-stretch">
		  <div class="col-lg-4 col-sm-6 offset-sm-3 offset-lg-0">
	      <div class="single-features h-100 text-left ">
				  <h3><i></i> Creating Cyber Rakshak</h3>
	        <p>Creating a Large Pool of Cyber Rakshak aligned to NIST NICE Framework for cyber resilience.</p>
	      </div>
	  	</div>
	  	<div class="col-lg-4 col-sm-6 offset-sm-3 offset-lg-0">
	      <div class="single-features h-100 text-left ">
		    	<h3><i></i> Research & Development</h3>
	      	<p>Mentor research work in Cyber Defense Engineering with active collaboration of Industry, Researcher & Academia. Create & Promote Made In India Technology in Cyber Defense Space.</p>
	      </div>
			</div>
	    <div class="col-lg-4 col-sm-6 offset-sm-3 offset-lg-0">
	      <div class="single-features h-100 text-left ">
				  <h3><i></i> Discussion & Discourse</h3>
	      	<p>Engage & Promote collaboration among Technology, Cyber Professional, industry Academia & Researchers through Webinars, Conferences, Symposium, Events.</p>
	      </div>
			</div>
		</div>
	</div>

	<div class="container">
		<!-- <h2 class="section_header text-warning"> Why Cybervidyapeeth? </h2> -->
		<h2 class="section_mega_header text-black mb-5 pt-5 pb-5"> Why Cybervidyapeeth? </h2>

		<div class="row mb-5">


			<div class="col-lg-3 col-sm-3 col-6 col-md-3">
				<div class="single-funfacts-box">
					<div class="icon">
              <img src="{% static 'cybervidyapeeth/images/funfacts-icon4.png' %}" alt="funfacts-icon">
          </div>
          <h3> 40+</h3>
          <p> Corporates </p>
				</div>
			</div>

			<div class="col-lg-3 col-sm-3 col-6 col-md-3">
				<div class="single-funfacts-box">
					<div class="icon">
              <img src="{% static 'cybervidyapeeth/images/funfacts-icon1.png' %}" alt="funfacts-icon">
          </div>
          <h3>10+</h3>
          <p> Universities</p>
				</div>
			</div>

			
			<div class="col-lg-3 col-sm-3 col-6 col-md-3">
				<div class="single-funfacts-box">
					<div class="icon">
              <img src="{% static 'cybervidyapeeth/images/funfacts-icon2.png' %}" alt="funfacts-icon">
          </div>
          <h3>11k+</h3>
          <p> Students Trained </p>
				</div>
			</div>

			
			<div class="col-lg-3 col-sm-3 col-6 col-md-3">
				<div class="single-funfacts-box">
					<div class="icon">
              <img src="{% static 'cybervidyapeeth/images/funfacts-icon3.png' %}" alt="funfacts-icon">
          </div>
          <h3>100+</h3>
          <p> Sessions Conducted </p>
				</div>
			</div>

			
			


		</div>
		<br/>
		<h2 class="section_mega_header text-black mt-5 mb-4"> 
			We reimage cyber-battle ready workforce
		</h2>
		<p class="text-center section_mega_p mb-5"> by training exceptional individuals from the finest Government and Private Entities</p>
			
		<div class="row">
			
			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/drdo.png' %}"/>	
				</div>
			</div>
			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/rbi.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/meity.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/npcil.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/ongc.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/powergrid.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/irctc.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/gail.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/sbi.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/ntpc.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/sail.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/iocl.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/tata-power.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/adani-power.png' %}"/>	
				</div>
			</div>

			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/cesc.png' %}"/>	
				</div>
			</div>


			<div class="col-6 col-sm-4 col-md-4 col-lg-3 ">
				<div class="corporate_customers">
					<img class="" src="{% static 'cybervidyapeeth/images/corporates/rbl-bank.png' %}"/>	
				</div>
			</div>

		</div>
	</div>
</section>

<section class="h-section light-section">
	<div class="container">
		<!-- <h2 class="section_header text-warning position-relative"> 
			Our Courses 
			<span class="text_shadow">Our Courses </span>
		</h2> -->
		<h2 class="section_mega_header text-black mb-5"> Our Offerings </h2>
		<div class="row mt-5 row mt-5 justify-content-center">
				

				<div class="col-12 col-sm-6 ">
					<a href="{% url 'website:courses' %}" class="card mega_course_card mx-auto" style="">
					  <img src="{% static 'cybervidyapeeth/images/programmer.jpg' %}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h5 class="card-title"> Cyber Defense Education </h5>
					    <!-- <p class="card-text">
					    	These are courses covering practical aspects of cyber security, hands on training along with degree/ diploma certificates by well known universities.
					    </p> -->
					    <!-- <div>
					    	<ul class="mb-0">
					    		<li> University Accredited </li>
					    		<li> Full Time </li>
					    		<li> Placement Assistance </li>
					    	</ul>
					    </div> -->
					  </div>
					  <button class="card-footer-btn btn">
					    See Details
					  </button>
					  

				  </a>
				</div>


				<div class="col-12 col-sm-6">
					<a href="{% url 'website:corporate_trainings' %}" class="card mega_course_card mx-auto" style="">
					  <img src="{% static 'cybervidyapeeth/images/cyber-1.jpg' %}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h5 class="card-title"> Cyber Defense  Trainings </h5>
					    <!-- <div>
					    	<ul class="mb-0">
					    		<li> Corporate Trainings </li>
					    		<li> Hands-On experience </li>
					    		<li> Certificate </li>
					    	</ul>
					    </div> -->
					  </div>
					  <button  class="card-footer-btn btn">
					    See Details
					  </button>

				  </a>
				</div>


		</div>
	</div>
</section>
<!-- 
<section class="h-section " style="min-height: 200px;">
	<div class="container">
		<h2 class="section_mega_header text-center"> Team </h2>

		<div class="row mt-4 justify-content-center">
			<div class="col-6 col-md-4 col-lg-3">
				<div class="card team_card mx-auto" style="">
					  <img src="{% static 'cybervidyapeeth/images/leadership/shashank-shekhar-garuryar.jpg' %}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h5 class="card-title"> Shashank Shekhar Garuryar </h5>
					    <div>
					    	<p> Chairman, Security Veteran</p>
					    </div>
					  </div>
			  </div>
			</div>
			<div class="col-6 col-md-4 col-lg-3">
			  <div class="card team_card mx-auto" style="">
					  <img src="{% static 'cybervidyapeeth/images/leadership/balaji-venkateshwar.jpg' %}" class="card-img-top" alt="...">
					  <div class="card-body">
					    <h5 class="card-title"> Balaji Venkateshwar</h5>
					    <div>
					    	<p>Chief Mentor, Cyber Defence</p>
					    </div>
					  </div>
			  </div>
			</div>
			
		</div>
	</div>
</section>
 -->
<section class="h-section light-section" style="min-height: 200px;">
	<div class="container">
		<h2 class="section_header text-center">Want to become a CyberRakshak? </h2>

		<div class="text-center mt-5">
			<a href="" class="btn btn-lg btn-warning enquiry_button_home" data-bs-toggle="modal" data-bs-target="#enquiryModal"> Apply Now! </a>
		</div>
	</div>
</section>




{% endblock base_block %}

{% block base_bottom_script %}
<script type="text/javascript" src="{% static 'cybervidyapeeth/libraries/OwlCarousel2-2.3.4/dist/owl.carousel.min.js' %}" ></script>


<script type="text/javascript">
	
</script>
{% endblock base_bottom_script %}

website/templates/website/url_template_mapping_template.html
{% extends 'website/base.html' %}
{% load static %}
{% load custom_tags_filters %}

{% block base_meta_block %}
    {{cv.page_data.meta_tags|safe}} 
{% endblock base_meta_block %}

{% block base_head_block %}
<link rel="stylesheet" type="text/css" href="{% static 'vajiramandraviweb/css/old_style.css' %}">
{% endblock base_head_block %}

{% block base_block %}
<div class="inner_page_intro_header">
  <div class="shadeoverlay"></div>
  <div class="container">
    <div class="content">
      <h1 class=""> {{cv.page_data.page_heading}}   </h1>
      <h2 class=""> by Vajiram &amp; Ravi  </h2>
    </div>
  </div>
</div>

{{cv.page_data.details|safe}}

{% endblock base_block %}